# Generated by Django 4.0 on 2023-06-09 05:23

from django.db import migrations
import treasuremap.fields


class Migration(migrations.Migration):

    dependencies = [
        ('places_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='placeremember',
            name='location',
            field=treasuremap.fields.LatLongField(blank=True, max_length=24, verbose_name='Карта'),
        ),
    ]
