# Generated by Django 3.0 on 2021-12-27 20:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='placetoremember',
            name='pub_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
